### ISSUE TITLE
No pyproject.toml (poetry) config file

### ISSUE THREAD

**Issue by hobson** [wq/django-data-wizard#40]
Projects using poetry for dependency and environment management might appreciate a `pyproject.toml` file. 
I'll issue a PR to add a `pyproject.toml`.
Also will add another `install_editable.sh` to `pip install --editable` from the `setup.py` file generated by poetry rather than the hardcoded one in the repository.

**Comment by sheppard** [comment]
Thanks for the prompt.  I finally added a pyproject.toml in f4e1600, using the newer standard `[project]` section for metadata.  The standard format should be compatible with a number of build backends, though it looks like Poetry's support is [still under development](https://github.com/python-poetry/roadmap/issues/3).

To integrate Django Data Wizard into an existing project, you should be able to install the pre-built package from PyPI, using Poetry or any tool of your choosing.  There are a number of ways to [customize Django Data Wizard](https://django-data-wizard.wq.io/config/) without installing it from source.

If you do need to fork and/or make contributions to Django Data Wizard, you can add a Poetry configuration to the fork - but for the main repository I will probably stick with setuptools since that's the standard configuration.  Once Poetry implements the `[project]` section in pyproject.toml you should be able to use it for developing DDW as well.
