### ISSUE TITLE
Failing URL lookup

### ISSUE THREAD

**Issue by SchrodingersGat** [wq/django-data-wizard#43]
Setting up a fresh install, with data-wizard `2.0.0`

After following the [setup instructions](https://django-data-wizard.wq.io/overview/setup) I am getting lost of URL reverse errors as follows:

![image](https://user-images.githubusercontent.com/10080325/210482708-bf61385c-6584-4dff-b965-ab13258a65e0.png)

![image](https://user-images.githubusercontent.com/10080325/210482735-0d23e7b1-3d39-449b-9e35-1157bc23e7b0.png)

![image](https://user-images.githubusercontent.com/10080325/210482684-d2383aba-d889-4696-8f18-2747a02d51e7.png)

I have the urlpatterns configured as per the docs:

![image](https://user-images.githubusercontent.com/10080325/210482884-ba5a785f-60a2-4f8d-bf8a-d75cbb542de6.png)

And the following in INSTALLED_APPS in settings.py:

![image](https://user-images.githubusercontent.com/10080325/210482920-746316cd-2577-4509-98f8-f119f8f9cc33.png)

Any suggestions where to start looking on this?

**Comment by SchrodingersGat** [comment]
Update: If I downgrade to data-wizard v1.3.0 I can progress past this step and it seems to be working as intended

**Comment by SchrodingersGat** [comment]
Any insight into why this is not working for the latest release?

**Comment by sheppard** [comment]
I have not been able to reproduce this - do you have a custom `TEMPLATES` or URL settings that might affect this?  What is the content of `data_wizard/urls.py`?

**Comment by SchrodingersGat** [comment]
@sheppard you can see our custom templates here: 

https://github.com/inventree/InvenTree/blob/9117c2234b69b144e5e569b628a04b28c780b005/InvenTree/InvenTree/settings.py#L320

> What is the content of data_wizard/urls.py?

I have not implemented a custom urls.py here, `data_wizard/urls.py` is (I am assuming) imported as part of the django-data-wizard library?

**Comment by sheppard** [comment]
Thanks, I think I have a good guess as to what is going on.  Something is probably causing `data_wizard.urls` to be imported before `data_wizard.apps.WizardConfig.ready()` is called.  If you move `"data_wizard"` higher in `INSTALLED_APPS` (perhaps right after `"django.contrib.admin"`), there is a good chance that it will work.  Could you confirm whether that fixes it - and if possible, identify the specific module that is causing URLs to be processed before all apps are ready?

This was not an issue in Django Data Wizard 1.3 because the tasks and URL routes were a preset list.  Now that there is an option to [override the task sequence](https://django-data-wizard.wq.io/config/tasks), the wizard's URLs aren't known until all potential tasks are autodiscovered.

Perhaps a more robust way to do this would be a wildcard path that Django Data Wizard resolves to a specific task, rather than trying to do it through the URL configuration.

**Comment by SchrodingersGat** [comment]
Thanks for the details. I have setup as you suggested - I've made a PR with the changes here - https://github.com/inventree/InvenTree/pull/5043

And, it works! (well, no errors so far at least)

Thanks for the advice, this really had me scratching my head. 

FYI if I put the import *below* this line, it fails:

https://github.com/inventree/InvenTree/blob/be6ab14c9bfc1b5387d6a7bbefdae9d46e5c1720/InvenTree/InvenTree/settings.py#L205

The plugin system exposes a custom set of URLs, based on what is loaded, so I guess it makes sense? Maybe?

**Comment by sheppard** [comment]
It looks like just importing the project urls file in an AppConfig.ready() will trigger this error.  For now, I added a [simple configuration](https://github.com/wq/django-data-wizard/blob/main/tests/source_app/apps.py) that reproduces the error, and logic in [data_wizard.urls](https://github.com/wq/django-data-wizard/blob/main/data_wizard/urls.py) to detect this case and suggest a solution.

Eventually we could try to get it to reinsert the final URLs (or use a wildcard route), but for the next release I think this is good enough.
